#!/bin/bash

interface=$1
duration=$2

rm /tmp/overlay-* 2&> /dev/null

echo "airodump-ng -w /tmp/overlay $interface" | at now


for((i=1; i<=$duration; i++))
do
  sleep 1
done

killall airodump-ng 2&> /dev/null

tail -n $(grep -n "Station" /tmp/overlay-01.csv | awk -F : '{print "+"$1+1}') /tmp/overlay-01.csv > /tmp/stations.overlay

rm /tmp/overlay-* 2&> /dev/null
