#!/bin/bash
#2013 - WiFiPineapple.com

#Function to find and reset the SD device
function reset_sd {
  DEVICE=$(find / -name idProduct -exec grep -l 6366 {} + | awk -F '/' '{ print $(NF-1) }')
  echo $DEVICE  > /sys/bus/usb/drivers/usb/unbind
  sleep 2
  echo $DEVICE  > /sys/bus/usb/drivers/usb/bind
}


touch /tmp/sd_format.progress

/etc/init.d/fstab stop

umount /dev/sda1

sleep 2

cat /pineapple/components/system/resources/includes/files/fdisk_instructions | fdisk /dev/sda

sleep 2

mkfs.ext4 /dev/sda1
mkfs.ext4 /dev/sda2


while [ $(ls /dev/ | grep -c sda2) == "0" ]
do
  sleep 1
done

mkswap /dev/sda2
swapon /dev/sda2

/etc/init.d/fstab start

rm /tmp/sd_format.progress
