#!/bin/bash

INFUSION=$1

touch /tmp/packager.status
cd /pineapple/components/infusions/
find ./$INFUSION -name "*.php" -exec grep -Lir "'/pineapple/includes/api/tile_functions.php'" {} \; | while read -r; do echo "<?php include_once('/pineapple/includes/api/tile_functions.php'); ?>" > /tmp/tmpfile; cat $REPLY >> /tmp/tmpfile; mv /tmp/tmpfile $REPLY; done;
tar -pczhf /tmp/$INFUSION.tar.gz $INFUSION

rm /tmp/packager.status